apiVersion: v1
kind: Service

metadata:
  name: enterprise-devsecops-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: enterprise-devsecops-app
    app.kubernetes.io/name: enterprise-devsecops-service
    app.kubernetes.io/part-of: enterprise-devsecops-platform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "enterprise-devsecops.chart" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: enterprise-devsecops-app

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http