apiVersion: v1
kind: Service

metadata:
  name: enterprise-devsecops-service
  namespace: enterprise-devsecops
  labels:
    app: enterprise-devsecops-app
    app.kubernetes.io/name: enterprise-devsecops-service
    app.kubernetes.io/part-of: enterprise-devsecops-platform

spec:
  type: ClusterIP

  selector:
    app: enterprise-devsecops-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http