name: Security Scanning

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  trivy-repository-scan:
    name: Trivy Repository Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan repository
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,misconfig
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

  trivy-image-scan:
    name: Trivy Container Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application image
        run: |
          docker build -t enterprise-devsecops-platform:security .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: enterprise-devsecops-platform:security
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0